/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playlist_ed;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author USER
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        UIManager.getDefaults().put("TableHeader.cellBorder" , BorderFactory.createEmptyBorder(0,0,0,0));
        ListaDePlayLists.getTableHeader().setOpaque(false);
        ListaDePlayLists.getTableHeader().setBackground(Color.WHITE);
        jScrollPane1.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDeNavegacion = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        OpcionPlayLists = new javax.swing.JPanel();
        OpcionTitulo = new javax.swing.JLabel();
        ElementosDeLista = new javax.swing.JLabel();
        TituloDePanel = new javax.swing.JLabel();
        PanelListaDePlayLists = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaDePlayLists = new javax.swing.JTable();
        PanelListaDeCanciones = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Playlist");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDeNavegacion.setBackground(new java.awt.Color(0, 0, 51));
        PanelDeNavegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/corchea_image.png"))); // NOI18N
        PanelDeNavegacion.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, 130));

        OpcionPlayLists.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        OpcionPlayLists.setOpaque(false);
        OpcionPlayLists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionPlayListsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OpcionPlayListsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OpcionPlayListsMouseExited(evt);
            }
        });
        OpcionPlayLists.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OpcionTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        OpcionTitulo.setForeground(new java.awt.Color(255, 255, 255));
        OpcionTitulo.setText("PlayLists");
        OpcionPlayLists.add(OpcionTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 25, -1, -1));

        PanelDeNavegacion.add(OpcionPlayLists, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 270, 70));

        getContentPane().add(PanelDeNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 600));

        ElementosDeLista.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        ElementosDeLista.setForeground(new java.awt.Color(0, 0, 0));
        ElementosDeLista.setText("N listas de reproducción");
        getContentPane().add(ElementosDeLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 130, 270, 30));

        TituloDePanel.setBackground(new java.awt.Color(153, 204, 255));
        TituloDePanel.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        TituloDePanel.setForeground(new java.awt.Color(0, 0, 0));
        TituloDePanel.setText("  Mis Playlist");
        TituloDePanel.setToolTipText("");
        TituloDePanel.setOpaque(true);
        getContentPane().add(TituloDePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 600, 200));

        PanelListaDePlayLists.setBackground(new java.awt.Color(255, 255, 255));
        PanelListaDePlayLists.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);

        ListaDePlayLists.setBackground(new java.awt.Color(255, 255, 255));
        ListaDePlayLists.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        ListaDePlayLists.setForeground(new java.awt.Color(0, 0, 51));
        ListaDePlayLists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nombre de PlayList", "# Canciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListaDePlayLists.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ListaDePlayLists.setFillsViewportHeight(true);
        ListaDePlayLists.setFocusable(false);
        ListaDePlayLists.setGridColor(new java.awt.Color(0, 0, 0));
        ListaDePlayLists.setIntercellSpacing(new java.awt.Dimension(0, 1));
        ListaDePlayLists.setRowHeight(75);
        ListaDePlayLists.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaDePlayLists.setShowGrid(true);
        ListaDePlayLists.setShowVerticalLines(false);
        ListaDePlayLists.setSurrendersFocusOnKeystroke(true);
        ListaDePlayLists.getTableHeader().setResizingAllowed(false);
        ListaDePlayLists.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ListaDePlayLists);
        if (ListaDePlayLists.getColumnModel().getColumnCount() > 0) {
            ListaDePlayLists.getColumnModel().getColumn(0).setResizable(false);
            ListaDePlayLists.getColumnModel().getColumn(0).setPreferredWidth(75);
            ListaDePlayLists.getColumnModel().getColumn(1).setResizable(false);
            ListaDePlayLists.getColumnModel().getColumn(1).setPreferredWidth(500);
            ListaDePlayLists.getColumnModel().getColumn(2).setResizable(false);
            ListaDePlayLists.getColumnModel().getColumn(2).setPreferredWidth(600);
        }

        PanelListaDePlayLists.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 380));

        getContentPane().add(PanelListaDePlayLists, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 600, 400));

        PanelListaDeCanciones.setBackground(new java.awt.Color(255, 255, 255));
        PanelListaDeCanciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PanelListaDeCanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpcionPlayListsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpcionPlayListsMouseClicked
        PanelListaDeCanciones.setVisible(false);
        PanelListaDePlayLists.setVisible(true);
        ListaDePlayLists.clearSelection();
    }//GEN-LAST:event_OpcionPlayListsMouseClicked

    private void OpcionPlayListsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpcionPlayListsMouseEntered
        OpcionPlayLists.setBackground(new Color(255,255,255,255));
        OpcionTitulo.setForeground(Color.BLACK);
        OpcionPlayLists.setOpaque(true);
        //OpcionTitulo.
    }//GEN-LAST:event_OpcionPlayListsMouseEntered

    private void OpcionPlayListsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpcionPlayListsMouseExited
        OpcionPlayLists.setBackground(new Color(255,255,255,0));
        OpcionTitulo.setForeground(Color.WHITE);
        OpcionPlayLists.setOpaque(false);
    }//GEN-LAST:event_OpcionPlayListsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ElementosDeLista;
    private javax.swing.JLabel LOGO;
    private javax.swing.JTable ListaDePlayLists;
    private javax.swing.JPanel OpcionPlayLists;
    private javax.swing.JLabel OpcionTitulo;
    private javax.swing.JPanel PanelDeNavegacion;
    private javax.swing.JPanel PanelListaDeCanciones;
    private javax.swing.JPanel PanelListaDePlayLists;
    private javax.swing.JLabel TituloDePanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
