/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playlist_ed;

/**
 *
 * @author USER
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDeNavegacion = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        ElementosDeLista = new javax.swing.JLabel();
        TituloDePanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Playlist");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDeNavegacion.setBackground(new java.awt.Color(0, 0, 51));
        PanelDeNavegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/corchea_image.png"))); // NOI18N
        PanelDeNavegacion.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, 130));

        getContentPane().add(PanelDeNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 600));

        ElementosDeLista.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        ElementosDeLista.setForeground(new java.awt.Color(0, 0, 0));
        ElementosDeLista.setText("N listas de reproducción");
        getContentPane().add(ElementosDeLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 130, 270, 30));

        TituloDePanel.setBackground(new java.awt.Color(153, 204, 255));
        TituloDePanel.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        TituloDePanel.setForeground(new java.awt.Color(0, 0, 0));
        TituloDePanel.setText("  Mis Playlist");
        TituloDePanel.setToolTipText("");
        TituloDePanel.setOpaque(true);
        getContentPane().add(TituloDePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 600, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ElementosDeLista;
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel PanelDeNavegacion;
    private javax.swing.JLabel TituloDePanel;
    // End of variables declaration//GEN-END:variables
}
