package playlist_ed;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;


public class MainFrame extends javax.swing.JFrame {

    Playlist[] playlistsDeEjemplo;
    
    
    public MainFrame() {
        initComponents();
        //Configuraciones visuales
        this.setLocationRelativeTo(null);
        UIManager.getDefaults().put("TableHeader.cellBorder" , BorderFactory.createEmptyBorder(0,0,0,0));
        ListaDePlayLists.getTableHeader().setOpaque(false);
        ListaDePlayLists.getTableHeader().setBackground(Color.WHITE);
        ListaDeCanciones.getTableHeader().setOpaque(false);
        ListaDeCanciones.getTableHeader().setBackground(Color.WHITE);
        jScrollPane1.setBorder(null);
        jScrollPane2.setBorder(null);
        
        
        //Creacion de las PlayList
        playlistsDeEjemplo=new Playlist[3];
        playlistsDeEjemplo[0]=new Playlist("PlayList1");
        playlistsDeEjemplo[1]=new Playlist("PlayList2");
        playlistsDeEjemplo[2]=new Playlist("PlayList3");
        actualizarVistaListaPlayList(playlistsDeEjemplo);   
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDeNavegacion = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        OpcionPlayLists = new javax.swing.JPanel();
        OpcionTitulo = new javax.swing.JLabel();
        ElementosDeLista = new javax.swing.JLabel();
        TituloDePanel = new javax.swing.JLabel();
        PanelListaDePlayLists = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaDePlayLists = new javax.swing.JTable();
        PanelListaDeCanciones = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaDeCanciones = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Playlist");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDeNavegacion.setBackground(new java.awt.Color(0, 0, 51));
        PanelDeNavegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/corchea_image.png"))); // NOI18N
        PanelDeNavegacion.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, 130));

        OpcionPlayLists.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        OpcionPlayLists.setOpaque(false);
        OpcionPlayLists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionPlayListsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OpcionPlayListsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OpcionPlayListsMouseExited(evt);
            }
        });
        OpcionPlayLists.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OpcionTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        OpcionTitulo.setForeground(new java.awt.Color(255, 255, 255));
        OpcionTitulo.setText("PlayLists");
        OpcionPlayLists.add(OpcionTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 25, -1, -1));

        PanelDeNavegacion.add(OpcionPlayLists, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 270, 70));

        getContentPane().add(PanelDeNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 600));

        ElementosDeLista.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        ElementosDeLista.setForeground(new java.awt.Color(0, 0, 0));
        ElementosDeLista.setText("N listas de reproducción");
        getContentPane().add(ElementosDeLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 130, 270, 30));

        TituloDePanel.setBackground(new java.awt.Color(153, 204, 255));
        TituloDePanel.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        TituloDePanel.setForeground(new java.awt.Color(0, 0, 0));
        TituloDePanel.setText("  Mis Playlist");
        TituloDePanel.setToolTipText("");
        TituloDePanel.setOpaque(true);
        getContentPane().add(TituloDePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 600, 200));

        PanelListaDePlayLists.setBackground(new java.awt.Color(255, 255, 255));
        PanelListaDePlayLists.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);

        ListaDePlayLists.setBackground(new java.awt.Color(255, 255, 255));
        ListaDePlayLists.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        ListaDePlayLists.setForeground(new java.awt.Color(0, 0, 51));
        ListaDePlayLists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Título de PlayList", "# Canciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListaDePlayLists.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ListaDePlayLists.setFillsViewportHeight(true);
        ListaDePlayLists.setFocusable(false);
        ListaDePlayLists.setGridColor(new java.awt.Color(0, 0, 0));
        ListaDePlayLists.setIntercellSpacing(new java.awt.Dimension(0, 1));
        ListaDePlayLists.setRowHeight(75);
        ListaDePlayLists.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaDePlayLists.setShowGrid(true);
        ListaDePlayLists.setShowVerticalLines(false);
        ListaDePlayLists.setSurrendersFocusOnKeystroke(true);
        ListaDePlayLists.getTableHeader().setResizingAllowed(false);
        ListaDePlayLists.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ListaDePlayLists);
        if (ListaDePlayLists.getColumnModel().getColumnCount() > 0) {
            ListaDePlayLists.getColumnModel().getColumn(0).setResizable(false);
            ListaDePlayLists.getColumnModel().getColumn(0).setPreferredWidth(75);
            ListaDePlayLists.getColumnModel().getColumn(1).setResizable(false);
            ListaDePlayLists.getColumnModel().getColumn(1).setPreferredWidth(400);
            ListaDePlayLists.getColumnModel().getColumn(2).setResizable(false);
            ListaDePlayLists.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        PanelListaDePlayLists.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 380));

        getContentPane().add(PanelListaDePlayLists, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 600, 400));

        PanelListaDeCanciones.setBackground(new java.awt.Color(255, 255, 255));
        PanelListaDeCanciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setOpaque(false);

        ListaDeCanciones.setBackground(new java.awt.Color(255, 255, 255));
        ListaDeCanciones.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ListaDeCanciones.setForeground(new java.awt.Color(0, 0, 51));
        ListaDeCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nombre de canción", "Fecha de lanzamiento", "Duración"
            }
        ));
        ListaDeCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ListaDeCanciones.setFillsViewportHeight(true);
        ListaDeCanciones.setFocusable(false);
        ListaDeCanciones.setGridColor(new java.awt.Color(0, 0, 0));
        ListaDeCanciones.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ListaDeCanciones.setRowHeight(50);
        ListaDeCanciones.setRowSelectionAllowed(false);
        ListaDeCanciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaDeCanciones.setShowGrid(true);
        ListaDeCanciones.setShowVerticalLines(false);
        ListaDeCanciones.setSurrendersFocusOnKeystroke(true);
        ListaDeCanciones.getTableHeader().setResizingAllowed(false);
        ListaDeCanciones.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(ListaDeCanciones);
        if (ListaDeCanciones.getColumnModel().getColumnCount() > 0) {
            ListaDeCanciones.getColumnModel().getColumn(0).setResizable(false);
            ListaDeCanciones.getColumnModel().getColumn(0).setPreferredWidth(75);
            ListaDeCanciones.getColumnModel().getColumn(1).setResizable(false);
            ListaDeCanciones.getColumnModel().getColumn(1).setPreferredWidth(400);
            ListaDeCanciones.getColumnModel().getColumn(2).setResizable(false);
            ListaDeCanciones.getColumnModel().getColumn(2).setPreferredWidth(200);
            ListaDeCanciones.getColumnModel().getColumn(3).setResizable(false);
        }

        PanelListaDeCanciones.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 580, 330));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("Debug");
        jRadioButton1.setBorder(null);
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.setFocusPainted(false);
        jRadioButton1.setFocusable(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        PanelListaDeCanciones.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 25, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordenar por nombre", "Ordenar por fecha", "Ordenar por duración" }));
        jComboBox1.setBorder(null);
        jComboBox1.setFocusable(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        PanelListaDeCanciones.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 170, -1));

        getContentPane().add(PanelListaDeCanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void actualizarVistaListaPlayList(Playlist[] playlists){
        PanelListaDeCanciones.setVisible(false);
        PanelListaDePlayLists.setVisible(true);
        TituloDePanel.setText("  Mis Playlist");
        ElementosDeLista.setText(playlistsDeEjemplo.length+" listas de reprodución");
        DefaultTableModel modelo=(DefaultTableModel)ListaDePlayLists.getModel();
        modelo.setRowCount(0);
        for (int i = 0; i < playlists.length; i++) {
            Object[] infoDePlaylist={
                i,playlists[i].getTitulo(),
                playlists[i].tamanio()+" canciones"
            };
            modelo.addRow(infoDePlaylist);
        }
        ListaDePlayLists.setModel(modelo);
    }
    
    public void actualizarVistaListaCanciones(Playlist playlist){
        PanelListaDeCanciones.setVisible(true);
        PanelListaDePlayLists.setVisible(false);
        TituloDePanel.setText("  Mis Playlist");
        ElementosDeLista.setText(playlistsDeEjemplo.length+" listas de reprodución");
    }
    
    private void OpcionPlayListsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpcionPlayListsMouseClicked
        actualizarVistaListaPlayList(playlistsDeEjemplo);
    }//GEN-LAST:event_OpcionPlayListsMouseClicked

    private void OpcionPlayListsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpcionPlayListsMouseEntered
        OpcionPlayLists.setBackground(new Color(255,255,255,255));
        OpcionTitulo.setForeground(Color.BLACK);
        OpcionPlayLists.setOpaque(true);
        //OpcionTitulo.
    }//GEN-LAST:event_OpcionPlayListsMouseEntered

    private void OpcionPlayListsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpcionPlayListsMouseExited
        OpcionPlayLists.setBackground(new Color(255,255,255,0));
        OpcionTitulo.setForeground(Color.WHITE);
        OpcionPlayLists.setOpaque(false);
    }//GEN-LAST:event_OpcionPlayListsMouseExited

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ElementosDeLista;
    private javax.swing.JLabel LOGO;
    private javax.swing.JTable ListaDeCanciones;
    private javax.swing.JTable ListaDePlayLists;
    private javax.swing.JPanel OpcionPlayLists;
    private javax.swing.JLabel OpcionTitulo;
    private javax.swing.JPanel PanelDeNavegacion;
    private javax.swing.JPanel PanelListaDeCanciones;
    private javax.swing.JPanel PanelListaDePlayLists;
    private javax.swing.JLabel TituloDePanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
